this-server:
  allow-editing: true
  remove-on-sneak: true
  spawn-on-join: true
  minutes-between-missions: 60

languages:
  prefix: "&6FlyingPets &7|&f "
  messages:
    levelup: "Your pet level up !"
    waitmission: "You need to wait &c{minutes}&f minute(s) to send your pet to mission !"
    nopermission: "&cYou don't have the permission !"
    missionsent: "Your pet earned &c200&r exp from the pet mission !"
  inventories:
    remove: "&cRemove"
    back: "&7Back"
    next: "&7Next page"
    previous: "&7Previous page"
    main:
      title: "&0FlyingPets"
      sendtomission: "&6Send to mission"
      spawnpet: "&fSpawn"
      removepet: "&cRemove"
      peteditor: "&fPetEditor"
    editor:
      enabled: "&aEnabled"
      disabled: "&7Disabled"
      editname: "&fGive it a name"
      spawnjoin: "&fSpawn on join"
  pets:
    levelprefix: " &7Lvl&f.&6{level}"
    wither: "&7Wither"
    pig: "&dPig"
    parrot: "&cParrot"
    squid: "&9Squid"
    armorstand: "&eArmorstand"
    sheep: "&fSheep"
    cow: "&2Cow"
    panda: "&fPanda"
    magmacube: "&cMagma &6Cube"
    cat: "&fCat"
    fox: "&6Fox"
    turtle: "&2Turtle"
    snowman: "&fSnowman"
    zombie: "&2Zombie"
    frog: "&aFrog"
    parachute: "&6Airman"
    bat: "&8Bat"
    dragon: "&0&k|&8Dragon&0&k|"