name: FlyingPets
author: Feeps
version: 0.1
api-version: 1.13
main: be.feeps.flying.Main
description: Flying pets that never stop following you
commands:
  flyingpets:
    description: Main command of FlyingPets
    aliases: [fpets, fpet, pet, pets, flyingpet]
    usage: /flyingpets